services:
  mariadb:
    image: mariadb:11
    container_name: japan-tours-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: japanuser
      MYSQL_PASSWORD: japanpass
    ports:
      - "3307:3306"      # ← เปลี่ยนจาก 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: